### ISSUE TITLE
No matching version found for call-bound@1.0.3

### ISSUE THREAD

**Issue by odovbysh** [ljharb/call-bound#2]
After the release of the new version, the restriction ceased to be available
![Annotation 2024-12-16 111414](https://github.com/user-attachments/assets/5c08d084-2d56-40b4-8fba-dd1d5d1580d7)

**Comment by odovbysh** [comment]
dont fix

**Comment by ljharb** [comment]
It’s definitely available, but sometimes new publishes take a few minutes for npm to make them fully available.
